version: "3.9"

services:
  fastapi:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: